DROP TABLE IF EXISTS users, materials, requests;

CREATE table IF NOT EXISTS users(
    user_id bigint generated by default as identity primary key,
    name varchar(64) NOT NULL,
    email varchar(64) NOT NULL,
    department_number int NOT NULL,
    role varchar(64) NOT NULL
);
CREATE unique index if not exists email_uindex ON users (email);

CREATE table IF NOT EXISTS materials(
    material_id bigint generated by default as identity primary key,
    name varchar(64) NOT NULL,
    description varchar(256) NOT NULL,
    unit varchar(64) NOT NULL,
    amount int NOT NULL
);

CREATE table IF NOT EXISTS requests(
    request_id bigint generated by default as identity primary key,
    user_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    material_id bigint REFERENCES materials (material_id) ON DELETE CASCADE,
    status varchar(256) NOT NULL,
    amount int NOT NULL,
    created_on timestamp without time zone
);
